---
name: SkyBlock
description: A powerful core for SkyBlock servers
author: GiantQuartz
website: twitter.com/GiantQuartz
main: room17\SkyBlock\SkyBlock
version: 2.2.6_modified-for-junxiesky
api:
- 3.0.0
...
